version: 2

sources:
  - name: raw_retail
    schema: raw
    description: "Raw Online Retail data loaded into Postgres schema raw."
    tables:
      - name: sales
        description: "Online Retail transactions (raw)."
