retail_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'retail_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'retail_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'retail') }}"
      schema: analytics
      threads: 4
